# Generated by Django 3.0.5 on 2022-05-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='em',
        ),
    ]
