# Generated by Django 4.0 on 2022-05-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220526_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='em',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
