# Generated by Django 3.0.5 on 2022-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourvariation',
            name='color',
            field=models.CharField(default='#000', max_length=50),
        ),
    ]
