# Generated by Django 3.0.5 on 2022-05-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
    ]
