# Generated by Django 4.0 on 2022-05-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_product_price'),
        ('cart', '0005_delete_newsletter'),
    ]

    operations = [
    ]
